### ISSUE TITLE
Xenial 621.134 and 621.135 release notes are missing

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-stemcell-rn#107]
Xenial stemcell releases 621.134 ([released to PivNet 2021-07-19](https://network.pivotal.io/products/stemcells-ubuntu-xenial/#/releases/925134)) and 621.135 ([released to PivNet 2021-07-21](https://network.pivotal.io/products/stemcells-ubuntu-xenial/#/releases/926145)) don’t have release notes @ https://github.com/pivotal-cf/docs-stemcell-rn/blob/master/stemcells.html.md.erb .

**Comment by mjgutermuth** [comment]
Thanks @coffee-squirrel! Our stemcell publishing bot had stopped working, but it's fixed now. The release notes are now up to date: https://docs.pivotal.io/stemcells/stemcells.html
