### ISSUE TITLE
Stemcells should ALWAYS be powered off

### ISSUE THREAD

**Issue by pivotal-manuel-morales** [pivotal-cf/docs-stemcell-rn#12]
Can we add a recommendation to keep the stemcells powered off.

**Comment by kartiklunkad26** [comment]
Apologies for this not being prioritized earlier. I think we have a good place to start documenting some of the practices. 

I'm going to review this with @bentarnoff

**Comment by mlimonczenko** [comment]
Hello @pivotal-manuel-morales,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
